### ISSUE TITLE
CBSS browse by subject/era: selecting a new subject keyword should jump to top of results list

### ISSUE THREAD

**Issue by wlpotter** [srophe/Gaddel#263]
When browsing by [subject](https://syriaca.org/cbss/browse.html?from=0&size=25&lang=en&q=cbssSubject&searchType=browse&letter=A&series=Comprehensive+Bibliography+on+Syriac+Studies) or [era](https://syriaca.org/cbss/browse.html?from=0&size=25&lang=en&q=cbssSubject&searchType=browse&letter=A&series=Comprehensive+Bibliography+on+Syriac+Studies), selecting an additional subject from the Related Subjects sidebar, or changing subjects by selecting one from the list included under each browse result, should jump users back to the top of the results list.

As it currently works, the results list changes but users may be halfway down the list and not see what it changed to, or how that affected their list of results.

**Comment by emgeier** [comment]
Resolved? Cannot reproduce

**Comment by wlpotter** [comment]
We can look at this at the meeting today, but I am still having the same issue. A good example for testing:

1. Select "Alexander Romance" from https://syriaca.org/cbss/browse.html
2. Scroll down in the results (enough so that the "Selected Subject" header is not visible
3. Select "Alexander the Great" from the subject list on the left column

The list of results changes, but the window stays in the same place on the page, so it's not clear what the currently selected keywords are, or how many results there are. Ideally, selecting a keyword would jump back to the top of the page so these are visible again

**Comment by emgeier** [comment]
Ah, so the viewer should jump top of the webpage rather than the top of the search results. Will do.
